package dangerorganization.poslovnopravilo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vozilo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String vrsta;
   private java.lang.String model;
   private java.lang.String motor;
   private java.lang.Integer cijena;

   public Vozilo()
   {
   }

   public java.lang.String getVrsta()
   {
      return this.vrsta;
   }

   public void setVrsta(java.lang.String vrsta)
   {
      this.vrsta = vrsta;
   }

   public java.lang.String getModel()
   {
      return this.model;
   }

   public void setModel(java.lang.String model)
   {
      this.model = model;
   }

   public java.lang.String getMotor()
   {
      return this.motor;
   }

   public void setMotor(java.lang.String motor)
   {
      this.motor = motor;
   }

   public java.lang.Integer getCijena()
   {
      return this.cijena;
   }

   public void setCijena(java.lang.Integer cijena)
   {
      this.cijena = cijena;
   }

   public Vozilo(java.lang.String vrsta, java.lang.String model,
         java.lang.String motor, java.lang.Integer cijena)
   {
      this.vrsta = vrsta;
      this.model = model;
      this.motor = motor;
      this.cijena = cijena;
   }

}