package dangerorganization.poslovnopravilo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vozilo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Vozilo() {
    }

}